# Generated by Django 3.0.4 on 2020-03-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=50)),
                ('callee', models.CharField(max_length=50)),
            ],
        ),
    ]
