# Generated by Django 3.0.4 on 2020-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0002_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('name', models.CharField(default='test', max_length=10)),
            ],
        ),
    ]
