# Generated by Django 3.0.4 on 2020-03-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0004_auto_20200306_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callee',
            name='token',
            field=models.CharField(max_length=250),
        ),
    ]
