# Generated by Django 3.0.4 on 2020-03-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0005_auto_20200306_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='callee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_parser.Callee'),
        ),
        migrations.AlterField(
            model_name='call',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_parser.EEG'),
        ),
        migrations.AlterField(
            model_name='callee',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='callee',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_parser.EEG'),
        ),
    ]
