# Generated by Django 3.0.4 on 2020-03-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0007_auto_20200306_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='callee',
            new_name='callee_id',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='caller',
            new_name='caller_id',
        ),
    ]
