# Generated by Django 3.0.4 on 2020-03-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0008_auto_20200306_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
    ]
