# Generated by Django 3.0.4 on 2020-03-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0009_delete_call'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Callee',
        ),
    ]
