# Generated by Django 3.0.4 on 2020-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0010_delete_callee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
