# Generated by Django 3.0.4 on 2020-03-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0011_callee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_parser.Callee')),
                ('caller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_parser.EEG')),
            ],
        ),
    ]
