# Generated by Django 3.0.4 on 2020-03-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_parser', '0012_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='callee_id',
            new_name='callee',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='caller_id',
            new_name='caller',
        ),
    ]
